version: '3.8'
services:
  web:
    build: .
    command: ["node", "main.js"]
    depends_on:
      - elasticsearch
    ports:
      - "3000:3000"
    env_file:
      - .env
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - discovery.type=single-node
      - TAKE_FILE_OWNERSHIP=true
    ports:
      - 9200:9200